# Generated by Django 5.0.4 on 2024-05-13 20:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('market', '0004_item_vendeur_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='grade',
        ),
    ]
